global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
  - job_name: 'model-server'
    metrics_path: /metrics
    static_configs:
      - targets: ['model-server:8001']
  - job_name: 'feature-calculator'
    metrics_path: /metrics
    static_configs:
      - targets: ['feature-calculator:8000']
